jwt:
  key: "YourSecretKeyHereYourSecretKeyHereYourSecretKeyHereYourSecretKeyHere"
  access-token-expiration-in-minutes: 10000
  refresh-token-expiration-in-days: 30

spring:
  docker:
    compose:
      file: backend/compose.yaml

  jpa:
    hibernate:
      ddl-auto: create-drop