jwt:
  key: "YourSecretKeyHereYourSecretKeyHereYourSecretKeyHereYourSecretKeyHere"
  access-token-expiration-in-minutes: 10000
  refresh-token-expiration-in-days: 30

spring:
  docker:
    compose:
      skip:
        in-tests: false
      enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/TalabaDB
    username: ilisi
    password: ilisi
  jpa:
    hibernate:
      ddl-auto: update